# Generated by Django 3.2.9 on 2021-11-28 13:34

from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('no_of_pages', models.IntegerField(null=True)),
                ('total_experience', models.FloatField(null=True)),
                ('college_name', system.models.SeparatedValuesField(null=True)),
                ('degree', system.models.SeparatedValuesField(null=True)),
                ('designation', system.models.SeparatedValuesField(null=True)),
                ('skills', system.models.SeparatedValuesField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('contactNo', models.CharField(max_length=14)),
                ('resumePath', models.FileField(upload_to='resumes/')),
                ('appliedOn', models.DateField(auto_now_add=True)),
                ('appliedFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.job', verbose_name='job applied for')),
            ],
        ),
    ]
