# Generated by Django 3.2.9 on 2021-12-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='ofCandidate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system.candidate', verbose_name='job application of'),
            preserve_default=False,
        ),
    ]
