# Generated by Django 3.2.9 on 2021-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_jobapplications_ofcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resumeMatched',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.DeleteModel(
            name='JobApplications',
        ),
    ]
