# Generated by Django 3.2.9 on 2021-12-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20211209_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resumeMatched',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
