# Generated by Django 3.2.9 on 2021-12-11 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_candidate_resumematched'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='addedOn',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
