# Generated by Django 3.2.9 on 2021-12-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_job_addedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='wcPath',
            field=models.FileField(null=True, upload_to='score_wc/'),
        ),
        migrations.AddField(
            model_name='job',
            name='desPath',
            field=models.FileField(null=True, upload_to='des_wc/'),
        ),
    ]
