# Generated by Django 3.2.9 on 2021-12-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20211211_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desPath',
            field=models.FileField(null=True, upload_to='templates/des_wc/'),
        ),
    ]
