# Generated by Django 3.2.9 on 2021-12-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_job_despath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='desPath',
        ),
    ]
